\c postgres;

CREATE TABLE IF NOT EXISTS wanted (
    id SERIAL PRIMARY KEY,
    wanted_name VARCHAR(255) NOT NULL,
    wanted_status VARCHAR(255) NOT NULL,
    dead_or_alive BOOLEAN NOT NULL,
    location VARCHAR(255),
    notes TEXT,
    bounty_value DECIMAL(10, 2)
);

INSERT INTO wanted (wanted_name, wanted_status, dead_or_alive, location, notes, bounty_value) VALUES
('Arthur Morgan', 'Procurado', false, 'Saint Denis', 'Líder em campo da gangue Van der Linde, habilidoso pistoleiro.', 5000.00),
('Dutch van der Linde', 'Procurado', false, 'Blackwater', 'Carismático líder da gangue, sempre com um plano.', 10000.00),
('John Marston', 'Capturado', true, 'Armadillo', 'Ex-membro da gangue Van der Linde, agora um homem da lei.', 3000.00),
('Micah Bell', 'Procurado', false, 'Strawberry', 'Traidor da gangue, violento e impiedoso.', 7000.00),
('Bill Williamson', 'Procurado', false, 'Tumbleweed', 'Explosivo e imprevisível, ex-soldado.', 4000.00),
('Javier Escuella', 'Procurado', false, 'Nuevo Paraíso', 'Mexicano, caçador de recompensas e pistoleiro habilidoso.', 4500.00),
('Charles Smith', 'Capturado', true, 'Valentine', 'Caçador e guerreiro leal à gangue.', 2500.00),
('Sadie Adler', 'Procurado', false, 'Rhodes', 'Viúva vingativa e ex-caçadora de recompensas.', 3500.00),
('Sean MacGuire', 'Procurado', false, 'Annesburg', 'Irlandês brigão e irreverente.', 2800.00),
('Lenny Summers', 'Procurado', false, 'Emerald Ranch', 'Jovem e promissor pistoleiro.', 3200.00),
('Hosea Matthews', 'Capturado', true, 'Saint Denis', 'Mentor da gangue, estrategista e golpista.', 2000.00),
('Trelawny', 'Procurado', false, 'Blackwater', 'Golpista sofisticado e manipulador.', 1500.00),
('Kieran Duffy', 'Capturado', true, 'Lagras', 'Ex-O’Driscoll, ganhou a confiança da gangue.', 1800.00),
('Leviticus Cornwall', 'Capturado', true, 'Saint Denis', 'Magnata industrial, alvo da gangue.', 6000.00),
('Angelo Bronte', 'Procurado', false, 'Saint Denis', 'Chefão do crime italiano.', 9000.00),
('Colm O’Driscoll', 'Procurado', false, 'Tall Trees', 'Líder cruel da gangue rival.', 8000.00),
('Milton', 'Capturado', true, 'Blackwater', 'Agente da Pinkerton, caçador implacável.', 5000.00),
('Edgar Ross', 'Procurado', false, 'Armadillo', 'Agente implacável do governo.', 5500.00),
('Landon Ricketts', 'Capturado', true, 'Chuparosa', 'Lendário pistoleiro do Velho Oeste.', 1000.00),
('Bonnie MacFarlane', 'Procurado', false, 'Hennigan’s Stead', 'Fazendeira determinada.', 1200.00),
('Herbert Moon', 'Capturado', true, 'Armadillo', 'Dono da loja, racista e conspirador.', 700.00),
('Josiah Trelawny', 'Procurado', false, 'Saint Denis', 'Charlatão e mestre do disfarce.', 2500.00),
('Pearson', 'Capturado', true, 'Blackwater', 'Cozinheiro da gangue, ex-marinheiro.', 800.00),
('Uncle', 'Procurado', false, 'Beecher’s Hope', 'Preguiçoso profissional, porém leal.', 500.00),
('Reverendo Swanson', 'Capturado', true, 'Valentine', 'Padre alcoólatra e jogador.', 600.00),
('Rains Fall', 'Procurado', false, 'Wapiti', 'Líder indígena pacifista.', 3000.00),
('Eagle Flies', 'Procurado', false, 'Wapiti', 'Guerreiro rebelde contra o governo.', 3500.00),
('Black Belle', 'Capturado', true, 'Bluewater Marsh', 'Pistoleira lendária e ex-fora da lei.', 1500.00),
('Slim Grant', 'Capturado', true, 'Valentine', 'Xerife honesto e destemido.', 1200.00),
('Jim Boy Calloway', 'Capturado', true, 'Saint Denis', 'Pistoleiro decadente e mentiroso.', 500.00),
('Flaco Hernandez', 'Procurado', false, 'Cotorra Springs', 'Assassino frio e calculista.', 4000.00),
('Emmet Granger', 'Procurado', false, 'New Austin', 'Ex-matador de búfalos, agora criminoso.', 2700.00),
('Billy Midnight', 'Capturado', true, 'Rhodes', 'Antigo pistoleiro, virou alcoólatra.', 1300.00),
('Granger Ford', 'Procurado', false, 'Hennigan’s Stead', 'Criminoso experiente e fugaz.', 2900.00),
('Buckley Tate', 'Procurado', false, 'Tumbleweed', 'Gângster notório no Novo México.', 3800.00),
('Cole Walker', 'Procurado', false, 'Tall Trees', 'Bandoleiro com fama de sanguinário.', 4100.00),
('Jebediah Stark', 'Capturado', true, 'Van Horn', 'Ex-soldado que virou fora da lei.', 2200.00),
('Otis Skinner', 'Procurado', false, 'Big Valley', 'Líder da gangue Skinner Brothers.', 5500.00),
('Clayton Boone', 'Procurado', false, 'Cholla Springs', 'Cavalheiro bandido, ex-oficial da guerra civil.', 2600.00),
('Gideon Price', 'Capturado', true, 'New Austin', 'Assaltante de trens experiente.', 2400.00),
('Silas Mercer', 'Procurado', false, 'Rhodes', 'Traficante de armas e contrabandista.', 4200.00),
('Jasper Finn', 'Procurado', false, 'Saint Denis', 'Gângster urbano e espião.', 4700.00),
('Preston Calloway', 'Capturado', true, 'Strawberry', 'Batedor de carteira profissional.', 1900.00),
('Augustus Briggs', 'Procurado', false, 'Annesburg', 'Mercenário contratado.', 3600.00),
('Victor Langley', 'Capturado', true, 'Lagras', 'Médico exilado, acusado de assassinato.', 1800.00),
('Luther Crow', 'Procurado', false, 'Beecher’s Hope', 'Misterioso assassino de xerifes.', 5300.00),
('Wes Dalton', 'Capturado', true, 'Tumbleweed', 'Último sobrevivente dos irmãos Dalton.', 2500.00);

